name: Dependency Vulnerability Scan

on:
  schedule:
    - cron: '0 0 * * SUN'   # tiap minggu
  push:
    branches: [ main ]
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          if [ -f composer.json ]; then
            composer install --no-progress --no-suggest --prefer-dist
          fi

      - name: Composer Security Audit
        run: |
          composer require --dev symfony/security-checker || true
          vendor/bin/security-checker security:check ./composer.lock