name: Secret Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan for secrets with TruffleHog
        uses: trufflesecurity/trufflehog@v3
        with:
          path: .
          pull-request: ${{ github.event.pull_request.number || '' }}